Update Master from Dev (#598)
* Update hyperion.py (#526)

- add "manufacturername"
- add "swversion"
- change light model
this fixes a problem in homeassistant trying to detect the manufacturer of the lights, misinterpreted as OSRAM.
https://github.com/diyhue/diyHue/pull/472

* Update hyperion.py (#526) (#527) (#530)

- add "manufacturername"
- add "swversion"
- change light model
this fixes a problem in homeassistant trying to detect the manufacturer of the lights, misinterpreted as OSRAM.
https://github.com/diyhue/diyHue/pull/472

Co-authored-by: juanesf <juanesf91@gmail.com>

Co-authored-by: Motea Marius <marius.motea@gmail.com>
Co-authored-by: juanesf <juanesf91@gmail.com>

* Implement HomeAssistant integration (#523)

Co-authored-by: foxy82 <foxy82.github@gmail.com>

* Add Debug Output Annotation "MQTT: "

* WLED Support (#531)

* Add Debug Output Annotation "MQTT: " (#2)

Co-authored-by: Mevel <4347330+Mevel@users.noreply.github.com>

* WLED support

- wled support by @gmallios
- rebased on HomeAssistant implementation

Co-Authored-By: Gregory Mallios <44323649+gmallios@users.noreply.github.com>

Co-authored-by: Mevel <4347330+Mevel@users.noreply.github.com>
Co-authored-by: Gregory Mallios <44323649+gmallios@users.noreply.github.com>

* update sw version to 1941132080

* Update homeassistant_ws.py (#549)

There is no such key alert in turn_on service. https://www.home-assistant.io/integrations/light/#service-lightturn_on

```voluptuous.error.MultipleInvalid: extra keys not allowed @ data['alert']```

* add option to use custom config path

* add arg description

* fix typo error

* use cwd if config_path not specified

* keep a copy of the certificate also in config path

* remove export folder

* check if srv and dst are not the same

* Return HTTP_PORT from os.getenv() as int (#557)

os.getenv always return a string. (line 90)
Port-number in server_class must be an int (line 1990).

This minor change makes sure that HOST_HTTP_PORT is an int when using environment-variable HTTP_PORT to avoid a crash at startup.

* add Branch select on Install

Choose Branch install promt added.
Choose between MASTER and DEV

* MQTT improvements (TLS, Plugs, Check availability) (#556)

* added more light_types (Lightstripes + Plug)

* MQTT improvements: TLS support, Plugs support, Check availability (if enabled in zigbee2mqtt) for unreachable-state, detect Lighstripes a litte bit more correct

* Changed line encoding for readable diff

* Changed line encoding for readable diff

* Use new astral library

* change Log Level for Deconz to Debug

elevate Loogin.info to logging.debug

* Use dedicted config path on volume mount

* add options in web interface for xiaomi motion sensor

* change default config path

* fix typo, update for openwrt, update host scripts ... (#569)

* update host scripts

- Add zeroconf 0.28.6 to the easy_install and install script (Wled dependency).
- Eliminate unnecessary spaces.
- Add Branch select on easy_install script. (from @Mevel )

* fix typo

- url_pices -> url_pieces
- pices -> pieces

* Fix entertainment stoppage

This fixes an issue stopping Entertainment, which announces that the area is still running.

* Add port reuse

- add reuse of port in entertainment
- add port reuse in scan host

* `is not` is deprecated...

- same as: https://github.com/diyhue/diyHue/issues/566

* Stop script when pressing ctrl-c

- when ctrl-c is pressed the emulator does not stop the script. Adding sys.exit() works

* Update for OpenWrt

- rename OpenWrt service name
- add branch select prompt to OpenWrt
- add zeroconf to OpenWrt

* Update Api and Swversion

- update swversion to 1941132080
- update api version to 1.39.0

* fix indentation error

File "/opt/hue-emulator/HueEmulator3.py", line 2026
    sys.exit()
             ^
TabError: inconsistent use of tabs and spaces in indentation

* Revert "Fix entertainment stoppage"

This reverts commit cc3916585dfa7bbd1ca0d3e3489c50820add9e69.

* Fix cert.pem had hardcoded path.  (#593)

* Update hyperion.py (#526) (#527)

- add "manufacturername"
- add "swversion"
- change light model
this fixes a problem in homeassistant trying to detect the manufacturer of the lights, misinterpreted as OSRAM.
https://github.com/diyhue/diyHue/pull/472

Co-authored-by: juanesf <juanesf91@gmail.com>

* Update README.md

experimental description updated

* Update README.md

* Update README.md

typo fix

* hotfix wrong docker arch pull (#555)

* Update Dockerfile

* add-architecture armhf

* try buster-slim

* remove "l" from arm version

Co-authored-by: Motea Marius <marius.motea@gmail.com>

* Fix #566 (#567)

Signed-off-by: Max Beckenbauer <max.bec92@gmail.com>

* fix: BridgeEmulator/web-ui-src/package.json & BridgeEmulator/web-ui-src/package-lock.json to reduce vulnerabilities (#529)

The following vulnerabilities are fixed with an upgrade:
- https://snyk.io/vuln/SNYK-JS-NODENOTIFIER-1035794

* change Log Level for Deconz to Debug

elevate Loglevel to Debug

* swversion update (#585)

For control over Hue App and full function control

* Fix cert.pem had hardcoded path. It is now expected to reside in the current working directory, which doesn’t change the behaviour in any way, but gives us more flexibility in case we need multiple instances.

Co-authored-by: Motea Marius <marius.motea@gmail.com>
Co-authored-by: juanesf <juanesf91@gmail.com>
Co-authored-by: Mevel <4347330+Mevel@users.noreply.github.com>
Co-authored-by: Max Beckenbauer <max.bec92@gmail.com>
Co-authored-by: Snyk bot <snyk-bot@snyk.io>
Co-authored-by: lnfactionfreddy <66081193+lnfactionfreddy@users.noreply.github.com>
Co-authored-by: Robert von Könemann <lordtaifleh@gmail.com>

* fix bug: color temp lights are added as dimmable

* fix conflict

* update swversion to version 1943185030

* Fix file error

Co-authored-by: juanesf <juanesf91@gmail.com>
Co-authored-by: Mevel <4347330+Mevel@users.noreply.github.com>
Co-authored-by: foxy82 <neil.renaud@gmail.com>
Co-authored-by: foxy82 <foxy82.github@gmail.com>
Co-authored-by: Gregory Mallios <44323649+gmallios@users.noreply.github.com>
Co-authored-by: zewelor <zewelor@gmail.com>
Co-authored-by: Heikki Henriksen <heikkih@gmail.com>
Co-authored-by: crietzschel <35508091+crietzschel@users.noreply.github.com>
Co-authored-by: U-PAYPOINT\MoteaM <MariusMotea@paypoint.com>
Co-authored-by: Robert von Könemann <vKnmnn@users.noreply.github.com>
Co-authored-by: Max Beckenbauer <max.bec92@gmail.com>
Co-authored-by: Snyk bot <snyk-bot@snyk.io>
Co-authored-by: lnfactionfreddy <66081193+lnfactionfreddy@users.noreply.github.com>
Co-authored-by: Robert von Könemann <lordtaifleh@gmail.com>