fix typo, update for openwrt, update host scripts ... (#569)
* update host scripts

- Add zeroconf 0.28.6 to the easy_install and install script (Wled dependency).
- Eliminate unnecessary spaces.
- Add Branch select on easy_install script. (from @Mevel )

* fix typo

- url_pices -> url_pieces
- pices -> pieces

* Fix entertainment stoppage

This fixes an issue stopping Entertainment, which announces that the area is still running.

* Add port reuse

- add reuse of port in entertainment
- add port reuse in scan host

* `is not` is deprecated...

- same as: https://github.com/diyhue/diyHue/issues/566

* Stop script when pressing ctrl-c

- when ctrl-c is pressed the emulator does not stop the script. Adding sys.exit() works

* Update for OpenWrt

- rename OpenWrt service name
- add branch select prompt to OpenWrt
- add zeroconf to OpenWrt

* Update Api and Swversion

- update swversion to 1941132080
- update api version to 1.39.0

* fix indentation error

File "/opt/hue-emulator/HueEmulator3.py", line 2026
    sys.exit()
             ^
TabError: inconsistent use of tabs and spaces in indentation

* Revert "Fix entertainment stoppage"

This reverts commit cc3916585dfa7bbd1ca0d3e3489c50820add9e69.