Tuple change reverted
Exception happened during processing of request from ('192.168.2.9', 60339)
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/lib/python3.5/http/server.py", line 422, in handle
    self.handle_one_request()
  File "/usr/lib/python3.5/http/server.py", line 410, in handle_one_request
    method()
  File "./HueEmulator3.py", line 1516, in do_PUT
    sendLightRequest(url_pices[4], put_dictionary)
  File "./HueEmulator3.py", line 547, in sendLightRequest
    xyValue = convert_xy(tuple(rgbValue))
TypeError: convert_xy() missing 2 required positional arguments: 'y' and 'bri'